import {Dimensions, StyleSheet} from 'react-native';
import { heightPixel, widthPixel } from '../../Utils/ResponsiveDimensions';

const {width, height} = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    backgroundColor: 'white',
  },
  search: {
    marginTop: height * 0.02,
    marginBottom: height * 0.01,
  },
  border: {
    height: height * 0.004,
    width: width,
    backgroundColor: '#D9D9D9',
    marginTop: height * 0.03,
    marginBottom: height * 0.015,
  },
  headerTxt: {
    fontSize: width * 0.05,
    fontFamily: 'Roboto',
    fontWeight: '900',
    color: 'black',
    margin: width * 0.005,
    left: 10,
  },
  txt: {
    fontSize: width * 0.05,
    fontFamily: 'Roboto',
    fontWeight: '900',
    color: 'black',
    marginTop: height * 0.015,
    justifyContent: 'flex-start',
    left: width * 0.02,
  },
  boxStl: {
    flexDirection: 'row',
    marginTop: height * 0.012,
    justifyContent: 'center',
  },
  box: {
    width: width * 0.41,
    height: height * 0.1,
    borderRadius: 9,
    backgroundColor: '#D9D9D9',
    marginRight: width * 0.01,
    padding: width * 0.03,
  },
  box2: {
    width: width * 0.45,
    height: height * 0.1,
    borderRadius: 9,
    backgroundColor: '#D9D9D9',
    marginLeft: width * 0.012,
  },
  num: {
    fontSize: width * 0.05,
    fontFamily: 'Roboto',
    fontWeight: '900',
    color: 'black',
  },
  sales: {
    fontSize: width * 0.035,
    fontFamily: 'Roboto',
    fontWeight: '900',
  },
  Icon: {
    marginLeft: width * 0.025,
    height: height * 0.031,
    width: width * 0.05,
  },
  box3: {
    width: width * 0.42,
    height: height * 0.1,
    borderRadius: 9,
    backgroundColor: '#D9D9D9',
    marginRight: width * 0.01,
    padding: width * 0.03,
    alignItems: 'center',
    justifyContent: 'center',
  },
  box4: {
    width: width * 0.45,
    height: height * 0.1,
    borderRadius: 9,
    backgroundColor: '#D9D9D9',
    marginLeft: width * 0.012,
    alignItems: 'center',
    justifyContent: 'center',
  },
  varify: {
    height: height * 0.03,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'white',
    borderRadius: 10,
    paddingHorizontal: width * 0.07,
    top: height * 0.005,
  },
  varification: {
    fontFamily: 'Roboto',
    fontWeight: '900',
    color: 'black',
  },
  containe: {
    flex: 1,
    backgroundColor: 'white',
    // marginBottom: 60,
  },
  searc: {
    marginTop: height * 0.02,
  },
  totalProduct: {
    height: heightPixel(48),
    width: widthPixel(375),
    margin: 20,
  },
  tx: {
    fontSize: 20,
    color: 'black',
    fontFamily: 'Roboto',
    fontWeight: '600',
  },
  resultBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  filter: {
    justifyContent: 'center',
    backgroundColor: '#F3F0F0',
    height: heightPixel(48),
    width: widthPixel(118),
    alignItems: 'center',
    flexDirection: 'row',
  },
  filterTxt: {
    color: 'black',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: widthPixel(10),
  },
  buttons: {
    flexDirection: 'row',
    height: heightPixel(70),
    justifyContent: 'center',
    alignItems: 'center',
  },
  cartbtn: {
    justifyContent: 'center',
    alignItems: 'center',
    height: heightPixel(54),
    width: widthPixel(182),
    backgroundColor: 'black',
    flexDirection: 'row',
    borderRadius: heightPixel(10),
    marginRight: widthPixel(10),
  },
  cartIcon: {
    color: 'white',
    alignSelf: 'center',
    marginRight: widthPixel(10),
  },
  cartTxt: {
    alignSelf: 'center',
    color: 'white',
    fontFamily: '600',
  },
  chackOutbtn: {
    justifyContent: 'center',
    alignItems: 'center',
    height: heightPixel(54),
    width: widthPixel(182),
    backgroundColor: 'black',
    flexDirection: 'row',
    borderRadius: heightPixel(10),
  },
  chackOuttext: {
    alignSelf: 'center',
    color: 'white',
    fontFamily: '600',
    marginRight: widthPixel(10),
  },
  chackOuticon: {
    color: 'white',
    alignSelf: 'center',
  },
  stickyButtons: {
    position: 'absolute',
    bottom: heightPixel(80),
    left: 0,
    right: 0,
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    borderTopWidth: 1,
    borderColor: '#ddd',
  },
});

export default styles;
