export const NavigationRoutes = {
    home:'Home',
    order:'Order',
    product:'Product',
    profile:'Profile',
    splash:'Splash',
    bottom: 'BootamTabNavigation',
    login:'Login',
    signup:'Signup',
    signuptow:'SignupTow',
    signupthree:'SignupThree',
    signupsuccess:'SignupSuccess',
    updatebanking:'UpdateBankingInformation',
    otpone:'OtpOne',
    otptow:'OtpTow',
}