export const Strings = {
  password: 'Password',
  email: 'Email',
  enterEmail: 'Enter your email',
  enterPassword: 'Enter your password',
  fullName: 'Full Name',
  enterfullName: 'Enter your full name',
  businessName: 'Business Name',
  enterBusiness: 'Enter your business name',
  product: 'Product Category',
  enterProduct: ' Enter your product category',
  phone: 'Phone Numbar',
  address: 'Address',
  enterphone: 'Entar your phone numbar',
  enteraddress: 'Enter your business address',
  accname: 'Account Holder Name',
  enteraccname: 'Enter Account Holder Name',
  accnum: 'Account Number',
  enteraccnum: 'Enter Account Number',
  ifsc: 'IFSC Code',
  enterifsc: 'Enter IFSC Coder (for bank transfer)',
  additional: 'Additional Details',
  enteradditional: 'Enter Payment Details(e.g. IBAN , PayPal)',

  SearchResults: 'Search Results',
  TotalProductAvailable: 'Total 28 Products Available',
  Filters: 'Filters',
  ViewCart: 'View Cart (1)',
  ChackOut: 'Chack Out',
  AddProduct: 'Add Product',
  UploadProductImage: 'Upload Product Image',
  EnterProductDescriptioan: 'Enter Product Description',
  Description: 'Description',
  Price: 'Price',
  Enter_Product_Price: 'Enter Product Price',
  Enter_Stock: 'Enter Stock',
  Enter_Product_Quantity: 'Enter Product Quantity',
  Add_Product: 'Add Product',
  EnterProductDescription: 'Enter Product Description',
};
